# Generated by Django 5.0.4 on 2024-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_remove_dashboardfilterobjectmodel_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardobjectmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
